# Generated by Django 4.1.5 on 2023-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
