# Generated by Django 4.1.5 on 2023-04-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('opnumber', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('doctor', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
