# Generated by Django 4.1.5 on 2023-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='limit',
            field=models.IntegerField(default=10),
        ),
    ]
